### ISSUE TITLE
Create Creature Class

### ISSUE THREAD

**Issue by Brotcrunsher** [pampersrocker/EvoNet#13]

**Comment by pampersrocker** [comment]
As mentioned in #15 
- [ ] Creatures went outside the generated Map

**Comment by Brotcrunsher** [comment]
Mentioned this in a current update video on my youtube channel already. Dont know if this should be handled as a bug though. Creatures react to places outside the map as if it would be water. So maybe the best idea is to just render additional water outside of the map.
