### ISSUE TITLE
Long term serialization

### ISSUE THREAD

**Issue by pampersrocker** [pampersrocker/EvoNet#34]
To save creatures in the long run without using up all available memory, dead creatures should be removed from memory and stored in a sqlite database for later data analysis.

**Comment by zettymaster** [comment]
why not put all save data in there?!
No akward multiple files to delete/copy if you want to make another run!

**Comment by pampersrocker** [comment]
For now a "graveyard" File is created which saves the current state of all Creatures died since the last save iteration. Tools may be created (a gravedigger :D ) to run queries on this created files.
