### ISSUE TITLE
CPU Auslastung aller Prozessoren immer bei 100%

### ISSUE THREAD

**Issue by Hannoma** [pampersrocker/EvoNet#43]
Hallo,
ich habe mir eben die neuste Version von EvoNet heruntergeladen.
Doch es laggt wie Sau und wie im Titel beschrieben, ist die CPU Auslastung die Ganze Zeit bei 100%.
Und da die letzte Version auf meinem Laptop, der um Einiges schlechter ist als mein PC, ohne große Ruckler lief, sollte es an der Performance meines PCs nicht liegen.

**Comment by fabiomokros** [comment]
Schalte in VS oben, links neben dem Start Button, von Debug auf Release. Das Sollte das Problem beheben. Brotcruncher in den Kommentaren von EvoNet [012]: "Das habe ich vergessen zu erwähnen: schalte seit multithreading unbedingt auf Release statt Debug oben."

**Comment by Hannoma** [comment]
Vielen Dank für die Hilfe. Läuft jetzt ohne Probleme ;)

**Comment by pampersrocker** [comment]
Sollte jetzt auch ohne release flüssig laufen (mit pull)
