### ISSUE TITLE
can you explain more please ?

### ISSUE THREAD

**Issue by ker2x** [pampersrocker/EvoNet#55]
what's evocommand ? 
is it ok to disable the graveyard (many GB of data in there) and what it's purpose ?
is evocommand a super fast multithreaded CLI while evonet is the slow version ?

Evonet and evocommand are both using the same world and creature ? i can run evocommand in the background (faster evolution) and switch to evonet to take a look at what they are doing ?

Also, what do i have to delete if i want to reset the simulation ?

thx :)

**Comment by pampersrocker** [comment]
You are correct.

Evocommand was created to run the project over a longer time, without overhead of rendering and as fast as possible (using a fixed timestep and not the actual time elapsed).
They both use the same version of the code (which is located in EvoSim). EvoNet and EvoCommand are different interfaces to the identical simulation.

The idea of the Graveyard was to run analysis how creatures evolve over time, but this was actually never implemented. Only the data of the creature is stored and a reference to the parent upon death of the creature. For the normal simulation you don't need to store the graveyard at all.

**Comment by ker2x** [comment]
hum, it crashed during the night. when i relaunch it, it take around 5~10mn to start, then it take more than 10s to save every 10s. it computing an average of 1 update/second instead of ~100000/s. (12c/24t amd threadripper). 

I'll try to find a way to recompile it and do some modification.
I tried with VS2018 but it failed, but i still have an old VS2015 install.

**Comment by ker2x** [comment]
hum, same problem. it say that evonet and evonetcontent are incompatible

**Comment by pampersrocker** [comment]
> 
> 
> hum, same problem. it say that evonet and evonetcontent are incompatible

That usually means that XNA Refresh is not properly installed into VS and it does not recognise the special XNA project type.

**Comment by ker2x** [comment]
ha yes XNA isn't installed. thx :)
